### ISSUE TITLE
GitLeaks takes too long to finish

### ISSUE THREAD

**Issue by Krlier** [globocom/huskyCI#435]
When running huskyCI on a large project, I came across an issue of GitLeaks taking too long to finish, approximately 23 minutes, as shown by the image below: 

![image](https://user-images.githubusercontent.com/40367872/70262232-bba3b480-1772-11ea-91a3-a99a02ece3eb.png)

I believe we need to code a solution that makes GitLeaks run faster and consequentially make huskyCI's stage faster on the developer's CI.

**Comment by rafaveira3** [comment]
Hey, @Krlier! Thanks for this feedback! At this moment we are considering contributing to [gitleaks](https://github.com/zricethezav/gitleaks) in order to have big projects (a huge number of commits)  run properly. 

Another option is testing [git-secret](https://github.com/awslabs/git-secrets) from AWS-Labs!
