### ISSUE TITLE
Install with Proxy problem

### ISSUE THREAD

**Issue by fabionoth** [globocom/huskyCI#499]
We try using huskyCI with proxy packages infrastructure and we replace some instalation codes. Basicly about FROM in dockerfiles. Follow changes:

 ```
[root@server huskyCI]# git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   client/cmd/main.go
#       modified:   deployments/docker-compose.yml
#       modified:   deployments/dockerfiles/api.Dockerfile
#       modified:   deployments/dockerfiles/db.Dockerfile
#       modified:   deployments/dockerfiles/enry/Dockerfile
#       modified:   deployments/dockerfiles/postgres.Dockerfile
#       modified:   deployments/dockerfiles/tfsec/Dockerfile
#       modified:   deployments/scripts/build-containers.sh
#       modified:   deployments/scripts/generate-local-token.sh
#       modified:   deployments/scripts/push-containers.sh
#
no changes added to commit (use "git add" and/or "git commit -a")
```

After that we try: 
```
[root@server huskyCI]# make run-client-linux
```
Follow error: 
```
go: github.com/onsi/ginkgo@v1.12.1: Get https://proxy.golang.org/github.com/onsi/ginkgo/@v/v1.12.1.mod: proxyconnect tcp: EOF
make: *** [build-client-linux] Error 1
```

Thanks to all

**Comment by rafaveira3** [comment]
Hey, @fabionoth! Thanks for reaching out to us. Glad to hear that you are trying to run huskyCI inside your company. 

I totally understand that you may need to change part of huskyCI containers to properly run inside your company. However, we are unable here to understand what changes you have made. 

By reading your `git status` output I realized that you haven't changed the `config.yaml` file, which [indicates which container image](https://github.com/globocom/huskyCI/blob/master/api/config.yaml#L3) huskyCI will pull when running the scans. If you are pushing your container to `mycompany/enry`, for example, you should edit this file as well.

Feel free to send us more details of your changes so that we can help you better! 🙃

**Comment by fabionoth** [comment]
I updated my images in `config.yml` file and

I try use that: 
`export GOPROXY=proxy-address:000`
```
root@server # make run-client-linux
go: github.com/onsi/ginkgo@v1.12.1: Get https://***:***@proxy-address:000/github.com/onsi/ginkgo/@v/v1.12.1.mod: EOF
make: *** [build-client-linux] Error 1
```

**Comment by rafaveira3** [comment]
Hey, @fabionoth! It indeed looks like you are having some issues with these certificates. The section `Securing your Docker API (recommended 🐼)` in our docs [here](https://huskyci.opensource.globo.com/docs/guides/install-in-my-org#securing-your-docker-api-recommended-) will guide you to have these settings up by there. If you desire, you can skip these steps when installing the Docker API in your current server.

**Comment by rafaveira3** [comment]
Sup, @fabionoth. I am closing this one for now due to long inactivity. Fell free to reopen it if you have any other question :)
